### ISSUE TITLE
For some reason ninja install doesn't work

### ISSUE THREAD

**Issue by SolarAquarion** [realh/roxterm#189]
I think you need to add a meson thing for installation

**Comment by SolarAquarion** [comment]
/usr/bin/convert /home/solaraquarion/build/roxterm-git/src/roxterm/Help/lib/roxterm_logo.png -geometry 16x16 ../Help/lib/favicon.ico
Traceback (most recent call last):
  File "/home/solaraquarion/build/roxterm-git/src/roxterm/maitch.py", line 3045, in run
    job.run()
  File "/home/solaraquarion/build/roxterm-git/src/roxterm/maitch.py", line 1603, in run
    self.__inner_run()
  File "/home/solaraquarion/build/roxterm-git/src/roxterm/maitch.py", line 1707, in __inner_run
    raise MaitchChildError("Rule '%s' failed" % r)
MaitchChildError: Rule '/usr/bin/convert /home/solaraquarion/build/roxterm-git/src/roxterm/Help/lib/roxterm_logo.png -geometry 16x16 ../Help/lib/favicon.ico' failed

but i'm getting this with the original install script

**Comment by realh** [comment]
I haven't finished work on the meson build system yet. It can build the code, which you can then run via the AppRun script, but I haven't started on the installation part yet. This is next on my list.

Meanwhile, the old build system is probably broken too because I've removed some source files etc and not bothered to update mscript.py. But the error you're getting looks like you might not have ImageMagick installed.

**Comment by SolarAquarion** [comment]
@realh it requires imagemagick 6.9

**Comment by realh** [comment]
Do you mean it doesn't work with imagemagick 7?

**Comment by SolarAquarion** [comment]
Yes

**Comment by realh** [comment]
Meson turned out to be too inflexible, I've ended up using CMake, and simplified things by checking the generated icons into git.
