### ISSUE TITLE
unexpected behavior on icewm startMinimized

### ISSUE THREAD

**Issue by gijsbers** [realh/roxterm#213]
In icewm one can set an option to start an application minimized like this:

```bash
$ grep startMinimized ~/.icewm/winoptions 
roxterm.Roxterm.startMinimized: 1
```

Roxterm reacts strangely to this. Either a mimized roxterm exists for a short while, as indicated by a button on the taskbar, but it quickly disappears. Or sometimes a roxterm does stay, but not minimized, but mapped. Apparently there is a timing issue which decides what will happen. In the latter case a _NET_ACTIVE_WINDOW message was sent to icewm to map the minimized window and icewm was quick enough to respond. The EWMH spec defines 3 message parameters in the data section:

1. A source indication.
2. A timestamp of last activitiy
3. The currently active window.

Roxterm always sends this as {1, 0, 0}, even if there was some other window, or event activity.

**Comment by realh** [comment]
I don't think I can do much about that. Roxterm doesn't directly interact with the window manager itself. The problem Roxterm faces is that setting the VTE widget's size in advance and letting GTK build the window around that just doesn't work, maybe because of the scrolling viewport. So Roxterm needs to set the window's default size before showing it. But to get the size right it has to measure all the borders and padding etc in the window hierarchy, including the window itself, and GTK doesn't provide any way to measure that stuff until the widgets are realized and packed. So the window gets realized with all its widgets, then a size negotiation is performed, then the top level size gets set before showing it. So these multiple steps are probably causing the inconsistent behaviour with icewm.
