### ISSUE TITLE
Followed INSTALL instruction but failed building it

### ISSUE THREAD

**Issue by abdulbadii** [realh/roxterm#226]
I followed INSTALL instruction but cannot go on smoothly:
```
user@hppavilion ~/Downloads/roxterm
$ cd build/
user@hppavilion ~/Downloads/roxterm/build
$ cmake ..
CMake Error: The source "/home/user/Downloads/roxterm/CMakeLists.txt" does not match the source "/home/user/Downloads/roxterm/src/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory
```
What should I do instead?

**Comment by realh** [comment]
It looks as if you have accidentally run cmake with the source directory set to `src` instead of the top-level directory. The easiest fix should be to delete everything in the `build` directory and try again. Another possibility is that cmake created its files in the top level instead of in `build`. Make sure the top-level and `src` contain none of these: `CMakeCache.txt`  `CMakeFiles`  `cmake_install.cmake`  `Makefile`.

**Comment by abdulbadii** [comment]
SOLVED !
by cleaning build/ in first place
THANKS MUCH!
