### ISSUE TITLE
Pasting Passwords Results in Authentication Errors

### ISSUE THREAD

**Issue by jlangson** [realh/roxterm#231]
How to reproduce:

1. `git push origin master`
2. Type your github name and press enter
3. Copy your password from a password manager like Bitwarden
4. press ctrl+shift+v
5. press enter

This results in the following error message
 "remote: Invalid username or password.
fatal: Authentication failed for ..."

When I use these exact steps in a different terminal like Konsole, I can authenticate correctly and `git push` works.

**Comment by realh** [comment]
Are you using a git version of vte? That had a bug recently which broke the clipboard, but it's fixed now. Otherwise, what happens if you paste while text is being echoed normally? Does the correct text get pasted then?

**Comment by jlangson** [comment]
As far as I know, I'm using regular git. Version 2.20.1 Git either came
installed with the OS I, I downloaded it from a debian repo.

Not sure how to test pasting when echoed normally. However, when I type
`git push origin master` The first prompt is for the username. While I had
been typing the username, something interesting happens when I paste the
username (ctrl+shift+v). If I copy 12345 and paste it into the username
prompt it displays `^[[200~12345^[[201~`

**Comment by realh** [comment]
I meant your version of vte, I think it's called libvte-2.91 on Debian. If you're using a packaged version that probably isn't the culprit, because I don't think that bug got into a release, which is why I was asking if you were using a more recent version downloaded with git.

When asking for the username, your input is being "echoed normally" ie what you type shows up on screen instead of being hidden because it's a password, so you've answered my second question in a roundabout way :-).

Googling the symptoms, I found [this stackexchange entry](https://unix.stackexchange.com/questions/196098/copy-paste-in-xfce4-terminal-adds-0-and-1); I hope it turns out to be that.

PS Even if you solve this problem, you'll probably find it useful to [use ssh with github](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh).

**Comment by jlangson** [comment]
vte is

/lib/x86_64-linux-gnu/libvte.so.9
/lib/x86_64-linux-gnu/libvte-2.91.so.0
/lib/x86_64-linux-gnu/libvte.so.9.2800.2
/lib/x86_64-linux-gnu/libvte-2.91.so.0.5400.2

These are the default versions that come with AntiX 19 (which is based on
debian buster).

Thanks for the tip about ssh.

**Comment by realh** [comment]
What about the bracketed paste issue though? Did the info from stackexchange help solve your problem?

**Comment by jlangson** [comment]
I don't have this problem anymore. I didn't take any specific steps but my
computer has been restarted multiple times as part of my normal use and the
problem went away.

**Comment by jlangson** [comment]
The problem has come back up, but running `reset` fixes it.
