### ISSUE TITLE
Upgrade from 3.14.3 -> 3.15.0 causes $TERM variable to not be set and all kinds of related issues

### ISSUE THREAD

**Issue by obadz** [realh/roxterm#258]
Downgrading back to 3.14.3 solves the issue. In 3.14.3, I see `$TERM` set as:

```
$ echo $TERM
xterm-256color
```

I'm on NixOS unstable and this is the upgrade PR is https://github.com/NixOS/nixpkgs/pull/291870

**Comment by realh** [comment]
3.15.0 isn't a valid release. I usually use x.y.0 as the base version for a pre-release with a new feature, because I think that makes more sense than the practice of using x.(y - 1).99. Then my full releases start with x.y.1. I generally apply the .0 tag at random, without caring whether things are correct at that point. I suppose I need to be more careful, and maybe change the format of beta tags.

The major new feature in 3.15.x is still under development, and is on a different branch. I was intending to hold off releasing for a while after merging to master, to test it for longer, but I suppose I could release early after all; the new feature will be turned off by default anyway.

**Comment by obadz** [comment]
Thanks, that's an odd convention but I guess it clears that up. Cheers.
