### ISSUE TITLE
Set Color Scheme via DBUS does not work

### ISSUE THREAD

**Issue by khambrecht** [realh/roxterm#270]
A few years ago I used a script to temporarily set the colors of the current terminal by switching to a different color scheme via DBUS and then change the colors of that scheme. I used the exact example from the manual:

`dbus-send --session /net/sf/roxterm/Options net.sf.roxterm.Options.SetColourScheme string:$ROXTERM_ID string:GTK
`

However, this no longer seems to work. The scheme does not change.

IIRC back in days where this did work I was running roxterm 3.3.x. Now I'm running 3.15.2

**Comment by khambrecht** [comment]
I have managed to compile an old code version of version 3.3.1, which I still had on disk. After I had started this old roxterm with the option `--replace`, changing the color scheme worked. And now it also works with the current version after running with `--replace`. Strange ....

**Comment by realh** [comment]
I'm not sure why that stopped working properly. To be honest the code has suffered from being hacked together over nearly 20 years, and the HTML guide has been neglected. This problem was probably caused by the recent addition of support for dark mode. You could try changing the "colour_scheme_light" and/or "colour_scheme_dark" settings in the current profile instead.

**Comment by khambrecht** [comment]
Good point. I did set the light/dark scheme in the current profile which was undefined previously. Maybe that did the trick.

I have been using roxterm for almost 10 years now. Thanks for this great tool.
